### ISSUE TITLE
Error while running ctpn_client.py

### ISSUE THREAD

**Issue by ebinzacharias** [wqt2019/ctpn_densenet-ocr#6]
The following error occurs when trying vtpn_client.py 

""
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "Input to reshape is a tensor with 947200 values, but the requested shape has 74000
""

Any solution?

**Comment by wqt2019** [comment]
sorry , some parameters is wrong , the default anchors  is [11, 16, 23, 33, 48, 68, 97, 139, 198, 283]. i change the anchors-num to 20 when i training the model . you can check the generate_anchors_tf_api.py and VGGnet_test.py.

**Comment by ebinzacharias** [comment]
> sorry , some parameters is wrong , the default anchors is [11, 16, 23, 33, 48, 68, 97, 139, 198, 283]. i change the anchors-num to 20 when i training the model . you can check the generate_anchors_tf_api.py and VGGnet_test.py.

Thank you for the quick response. 
Yes, I thought the same and changed the anchor numbers to default (as I trained the model with anchor num = 10) before converting to servable model. However, that still showed the same error but with a different set of values. I will check again. 
I only want to use the CTPN serving and that is running error-less with the ctpn_client.py, isn't it?

**Comment by wqt2019** [comment]
tf-serving is very hard to debug, so you can send your model and parameters to my email : 594063909@qq.com

**Comment by wqt2019** [comment]
or upload to the baidu cloud && google cloud

**Comment by ebinzacharias** [comment]
> parameters

I have sent you an email. Thanks again.
